// patchGenreMap.js
// Run with: node scripts/patchGenreMap.js

const fs = require("fs");
const path = require("path");

const mapPath = path.join(__dirname, "./genreMap.js");

// Read current genreMap
const raw = fs.readFileSync(mapPath, "utf8");
const match = raw.match(/const genreMap = ({[\s\S]*?});\s*module\.exports/);
if (!match) {
  console.error("Could not parse genreMap.js — check the file format.");
  process.exit(1);
}

const genreMap = JSON.parse(match[1]);
console.log(`Loaded ${Object.keys(genreMap).length} existing entries.`);

// Manual corrections for the 44 unknowns
const corrections = {
  "J. S. Bach": "Classical",
  "ELP": "Progressive Rock",
  "Rostropovich": "Classical",
  "Skip Spence": "Folk Rock",
  "Tony Williams Lifetime": "Jazz Fusion",
  "Bill Evans & Monica Zetterlund": "Jazz",
  "Somi": "Jazz",
  "Yahzarah": "Neo Soul",
  "Toninhohorta": "Brazilian Jazz",
  "Moistboyz": "Rock",
  "Björk & Tríó Guðmundar Ingólfssonar Guðmundsdóttir": "Art Pop",
  "John Luther Adams": "Contemporary Classical",
  "Ensemble Organum": "Early Music",
  "Luca Marenzio": "Classical",
  "Christian Borle": "Musical Theatre",
  "David Hyde Pierce & Ensemble": "Musical Theatre",
  "Ensemble & Michael MCGrath": "Musical Theatre",
  "Ensemble & Hank Azaria": "Musical Theatre",
  "Sara Ramirez": "Musical Theatre",
  "Christian Borle, David Hyde Pierce, Ensemble & Hank Azaria": "Musical Theatre",
  "Christopher Sieber & Sara Ramirez": "Musical Theatre",
  "Christopher Sieber, David Hyde Pierce, Hank Azaria, Michael MCGrath, Steve Rosen & Tim Curry": "Musical Theatre",
  "Christopher Sieber, David Hyde Pierce, Ensemble, Hank Azaria, Michael MCGrath, Sara Ramirez, Steve Rosen & Tim Curry": "Musical Theatre",
  "Christopher Sieber, Company, David Hyde Pierce, Ensemble, Hank Azaria, Michael MCGrath, Steve Rosen & Tim Curry": "Musical Theatre",
  "Brad Bradley, David Hyde Pierce, Emily Hsu & Greg Reuter": "Musical Theatre",
  "Christian Borle, Christopher Sieber, David Hyde Pierce, Ensemble & Hank Azaria": "Musical Theatre",
  "Andrew Gorny": "Independent",
  "Kaare Norge": "Jazz",
  "Petteri Sariola": "Acoustic Guitar",
  "Soulfood 76": "Soul",
  "Earl Greyhound": "Rock",
  "Jon Connor": "Hip-Hop",
  "Socrates": "Rock",
  "Tig Notaro": "Comedy",
  "CART!": "Independent",
  "POWER TOOLS": "Jazz Fusion",
  "Piano Overlord": "Electronic",
  "Guitarwar": "Rock",
  "Dimotika": "World Music",
  "Mixalis Tzouganakis": "World Music",
  "Dan Hyer": "Independent",
  "Christie Lenee": "Acoustic",
  "Biscuits & Gravy": "Independent",
  "Biscuits & Gravy m4a": "Independent",
};

// Apply corrections
let applied = 0;
for (const [artist, genre] of Object.entries(corrections)) {
  genreMap[artist] = genre;
  applied++;
}

// Write back
const content = `// Auto-generated by enrichGenres.js — feel free to manually correct any entries\nconst genreMap = ${JSON.stringify(genreMap, null, 2)};\nmodule.exports = genreMap;\n`;
fs.writeFileSync(mapPath, content, "utf8");

console.log(`Applied ${applied} corrections.`);
console.log(`Unknown remaining: ${Object.values(genreMap).filter(v => v === "Unknown").length}`);
console.log("genreMap.js saved successfully.");